sudo: false

addons:
 apt:
   packages:
     - graphviz

language: scala

jdk:
  - oraclejdk8

before_install:
  - wget --quiet --output-document=/tmp/AMD-SDK.tar.bz2 http://cs.wisc.edu/~riccardo/assets/AMD-APP-SDKInstaller-v3.0.130.136-GA-linux64.tar.bz2
  - mkdir /tmp/amd-app-sdk-installer
  - tar -xjf /tmp/AMD-SDK.tar.bz2 -C /tmp/amd-app-sdk-installer
  - export AMDAPPSDK=${HOME}/AMDAPPSDK
  - export OPENCL_VENDOR_PATH=${AMDAPPSDK}/etc/OpenCL/vendors
  - mkdir -p ${OPENCL_VENDOR_PATH}
  - sh /tmp/amd-app-sdk-installer/AMD-APP-SDK*.sh --tar -xf -C ${AMDAPPSDK}
  - echo libamdocl64.so > ${OPENCL_VENDOR_PATH}/amdocl64.icd
  - export LD_LIBRARY_PATH=${AMDAPPSDK}/lib/x86_64/sdk:${LD_LIBRARY_PATH}
  - chmod +x ${AMDAPPSDK}/bin/x86_64/clinfo
  - ${AMDAPPSDK}/bin/x86_64/clinfo
    
before_cache:
  - find $HOME/.sbt -name '*.lock' -delete
  - find $HOME/.ivy2 -name 'ivydata-*.properties' -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_script:

script:
  - sbt +test

before_deploy:

deploy:
  skip_cleanup: true
  provider: script
  script: sbt "release with-defaults"
  on:
    condition: -e ./deploy.sbt
    all_branches: true
